---
- name: Converge
  hosts: all
  tasks:
    - name: "Include wandansible.prometheus_exporter.mtail"
      ansible.builtin.include_role:
        name: "wandansible.prometheus_exporter.mtail"
      vars:
        mtail_exporter_github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"

        mtail_exporter_logs:
          - "/var/log/lastlog"
